artifact_root: artifact

data_ingestion:
    data_ingestion_dir: artifact/data_ingestion
    source_url: sureshgupta/health-insurance-data-set
    local_data_file: artifact/data_ingestion/1651277648862_healthinsurance.csv
    train_file_path: artifact/data_ingestion/train.csv
    test_file_path: artifact/data_ingestion/test.csv
    
    
data_validation:
    data_validation_dir: artifact/data_validation
    STATUS_FILE : artifact/data_validation/status.txt
    

data_transformation:
    transformed_data_dir: artifact/data_transformation
    transformed_train_file_path: artifact/data_transformation/train.npy
    transformed_test_file_path: artifact/data_transformation/test.npy
    transformed_object_file_path: artifact/data_transformation/preprocessor.pkl

model_trainer:
    model_trainer_dir: artifact/model_trainer
    trained_model_file_path: artifact/model_trainer/model.pkl

model_evaluation:
    model_evaluation_dir: artifact/model_evaluation
    metric_file_path : artifact/model_evaluation/metrics.json
