features:
  - smoker
  - diabetes
  - regular_ex

models:
  # LinearRegression: LinearRegression()
  Ridge: Ridge()
  # Lasso: Lasso()
  DecisionTreeRegressor: DecisionTreeRegressor()
  RandomForestRegressor: RandomForestRegressor()
  KNeighborsRegressor: KNeighborsRegressor()
  XGBRegressor: XGBRegressor()

param:
  # LinearRegression: ~
  Ridge:
    alpha:
      - 1
      - 2
      - 3
  # Lasso: ~
  DecisionTreeRegressor:
    criterion:
      - squared_error
      - friedman_mse
      - absolute_error
      - poisson
    splitter:
      - best
      - random
    max_depth: 
      - 100
      - 200
      - 300
  RandomForestRegressor:
    max_features:
      - 0.25
      - 0.5
      - 0.75
      - 1
    max_depth:
      - 50
      - 100
      - 150 
      - 200
    n_estimators:
      - 50
      - 100
      - 150 
      - 200
  KNeighborsRegressor:
    n_neighbors:
      - 5
      - 10
      - 15
    weights:
      - distance
      - uniform
  XGBRegressor:
    learning_rate:
      - 0.1
      - 0.01
      - 0.05
      - 0.001
    n_estimators:
      - 100
      - 200
      - 300
    max_depth:
      - 3
      - 6
      - 9
      
test_size: 0.2